#define TAPPING_TOGGLE 2

// #define PERMISSIVE_HOLD
#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_TIME_TO_MAX 50

#define SPLIT_LAYER_STATE_ENABLE

#define RGB_MATRIX_TIMEOUT 300000 // 300 * 1000ms = 5min
